baseurl = "/"
languageCode = "en-gb"
title = "Axel Segebrecht: Holistic digital problem-solver"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 3

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Axel Segebrecht"
	description = "Holistic digital problem-solver"

	# Format dates with Go's time formatting
	date_format = "2016-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "asset.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Axel**, a digital consultant who takes a holistic approach to solving complex business problems."
		# The icons will be shown if you enter your username
		twitter = "axelsegebrecht"
		github = "axelsegebrecht"
		dribbble = ""
		facebook = "asegebrecht"
		googleplus = ""
		flickr = ""
		linkedin = "axelsegebrecht"

		copyright = [
			"Content and code available under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (BY-NC-SA) by Axel Segebrecht, unless stated otherwise",
			"Design based on [HTML5 UP](//html5up.net)",
			"A lot of images supplied by [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Finding straight-forward answers to complex questions"
		content = "Seeing a clear path and understanding which option to choose is what I have done for over 18 years whilst working dedicatedly with individual professionals, directors and large enterprises such as Universities. You can rely on me to design and deliver big web projects, managing a portfolio of projects and aligning business processes to leverage the latest technology.<br><br>I work on a retained basis, ad-hoc or as part of a longer term project, easily from remote or on-site. [Get in touch](/#contact-form) to find out more."


	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Securely encrypted communication is available if requested. Please send a text message to my phone number or find me on Signal, Telegram or iMessage. The form on this website is provided for your convenience and is using SSL. Your message is send in the open and is not encrypted."

		address = [
			"Bletchley",
			"Milton Keynes, MK2",
			"United Kingdom"
		]
		phone = "+44.7794132161"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "axel@segebrecht.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Articles"
	url  = "post/"
	weight = 10

[[menu.main]]
	name = "Public Speaking"
	url  = "public-speaking/"
	weight = 10
